name: Tartufo Scan
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Tartufo Scan
        uses: godaddy/tartufo-action@4.1.0
        